# Generated by Django 4.2 on 2024-05-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                related_name="posts", to="posts.tag", verbose_name="Тег"
            ),
        ),
        migrations.AddField(
            model_name="favorites",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="favorites",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="favorites",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="uniquefavorit"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorites",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("post")), _negated=True),
                name="favoriteuniq",
            ),
        ),
    ]
