# Generated by Django 4.2 on 2024-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorites",
            name="status",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
