# Generated by Django 4.2 on 2024-05-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_author_alter_post_tag"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorites",
            name="favoriteuniq",
        ),
    ]
